[unix_http_server]
file=/run/supervisord.sock
chmod=0700
chown=root:root
username=app
password=appServer123

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
logfile=/dev/null
pidfile=/run/supervisord.pid
nodaemon=true
user=root
logfile_maxbytes=0

[supervisorctl]
serverurl=unix:///run/supervisord.sock
username=app
password=appServer123

[include]
files = /etc/supervisord.d/*.ini /etc/supervisord.custom.d/*.ini